#!/bin/bash
# cfront-run.sh <testfile.C>
# Build cfront-3 if needed, then translate + compile + run a C++ file.
set -u
export PATH=/c/msys64/usr/bin:$PATH
cd "$(dirname "$0")"      # repo root

GPP=/c/msys64/usr/bin/g++.exe
GCC=/c/msys64/usr/bin/gcc.exe
TC="${1:-demo/shapes.C}"
CDIR="$(dirname "$TC")"
BASE="$(basename "$TC" .C)"

hr(){ echo "======================================================="; }

# 1. incl junction
[ -e incl ] || cmd //c "mklink /J incl incl-master\\incl-linux32" >/dev/null 2>&1

# 2. translator + munch
if [ ! -x cfront.exe ]; then
  echo "--- building cfront (one-time) ---"
  make -C src CXX=$GPP >/tmp/cfront_build.log 2>&1 || { echo "cfront build FAILED, see /tmp/cfront_build.log"; exit 1; }
fi
[ -x munch.exe ] || $GCC -std=gnu89 -w -o munch _munch/munch.c
echo "cfront.exe: $(ls -la cfront.exe | awk '{print $5}') bytes   munch.exe: $([ -x munch.exe ] && echo ok)"

# 3. runtime library (needed to LINK/run).
#    The full stream/new/static library is large; for demos we provide a
#    minimal runtime (_main + vector helpers) that links programs which don't
#    use static constructors or iostreams.
if [ ! -f libC.a ]; then
  echo "--- building minimal libC.a runtime ---"
  cat > /tmp/_cfront_rt.c <<'RT'
#include <stdlib.h>
void  _main(void)               {}
void  __vec_new(void)           {}
void  __vec_delete(void)        {}
void* __nw__FUl(unsigned long n){ return malloc(n); }   /* operator new    */
void  __dl__FPv(void* p)        { free(p); }            /* operator delete */
RT
  $GCC -w -std=gnu89 -c /tmp/_cfront_rt.c -o /tmp/_cfront_rt.o && ar rc libC.a /tmp/_cfront_rt.o
fi

echo; hr; echo " 1) C++ SOURCE  ($TC)"; hr
cat "$TC"

echo; hr; echo " 2) C GENERATED BY CFRONT"; hr
# -Fc prints the translated C to stdout; strip #line noise for readability
if ./CC -Fc "$TC" > /tmp/cfront_c.out 2> /tmp/cfront_err.log; then
  grep -v '^#' /tmp/cfront_c.out | cat -s
else
  echo "cfront reported errors:"; grep -viE 'which:|redefined|note:' /tmp/cfront_err.log
fi

echo; hr; echo " 3) COMPILE + LINK + RUN"; hr
if [ -f libC.a ]; then
  if ./CC "$TC" -o "$CDIR/$BASE" 2>/tmp/cc_link.log; then
    echo "--- program output ---"
    "$CDIR/$BASE.exe"
    echo "--- exit code: $? ---"
  else
    echo "link failed:"; cat /tmp/cc_link.log
  fi
else
  echo "(libC.a not built - showing translation only)"
fi
