; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35228.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	__ptbl_vec___c_Users_Diana_pg_cfront_3_demo_zoo_C_
PUBLIC	__vtbl__4Bird___c_Users_Diana_pg_cfront_3_demo_zoo_C
PUBLIC	__vtbl__3Dog___c_Users_Diana_pg_cfront_3_demo_zoo_C
PUBLIC	__vtbl__6Animal___c_Users_Diana_pg_cfront_3_demo_zoo_C
_DATA	SEGMENT
COMM	__cfront_version_303_xxxxxxxx:BYTE
_DATA	ENDS
_DATA	SEGMENT
__ptbl_vec___c_Users_Diana_pg_cfront_3_demo_zoo_C_ DQ FLAT:__vtbl__6Animal___c_Users_Diana_pg_cfront_3_demo_zoo_C
	DQ	FLAT:__vtbl__3Dog___c_Users_Diana_pg_cfront_3_demo_zoo_C
	DQ	FLAT:__vtbl__4Bird___c_Users_Diana_pg_cfront_3_demo_zoo_C
	ORG $+8
__vtbl__4Bird___c_Users_Diana_pg_cfront_3_demo_zoo_C DW 00H
	DW	00H
	ORG $+4
	DQ	0000000000000000H
	DW	00H
	DW	00H
	ORG $+4
	DQ	FLAT:__dt__4BirdFv
	DW	00H
	DW	00H
	ORG $+4
	DQ	FLAT:sound__4BirdFv
	DW	00H
	DW	00H
	ORG $+4
	DQ	FLAT:kind__4BirdFv
	DW	00H
	DW	00H
	ORG $+4
	DQ	0000000000000000H
__vtbl__3Dog___c_Users_Diana_pg_cfront_3_demo_zoo_C DW 00H
	DW	00H
	ORG $+4
	DQ	0000000000000000H
	DW	00H
	DW	00H
	ORG $+4
	DQ	FLAT:__dt__3DogFv
	DW	00H
	DW	00H
	ORG $+4
	DQ	FLAT:sound__3DogFv
	DW	00H
	DW	00H
	ORG $+4
	DQ	FLAT:kind__3DogFv
	DW	00H
	DW	00H
	ORG $+4
	DQ	0000000000000000H
__vtbl__6Animal___c_Users_Diana_pg_cfront_3_demo_zoo_C DW 00H
	DW	00H
	ORG $+4
	DQ	0000000000000000H
	DW	00H
	DW	00H
	ORG $+4
	DQ	FLAT:__dt__6AnimalFv
	DW	00H
	DW	00H
	ORG $+4
	DQ	FLAT:sound__6AnimalFv
	DW	00H
	DW	00H
	ORG $+4
	DQ	FLAT:kind__6AnimalFv
	DW	00H
	DW	00H
	ORG $+4
	DQ	0000000000000000H
_DATA	ENDS
PUBLIC	main
PUBLIC	__real@3ff0000000000000
PUBLIC	__real@4000000000000000
PUBLIC	__real@4008000000000000
PUBLIC	__real@4010000000000000
EXTRN	__nw__FUl:PROC
EXTRN	__dl__FPv:PROC
EXTRN	printf:PROC
EXTRN	_main:PROC
EXTRN	__GSHandlerCheck:PROC
EXTRN	__security_check_cookie:PROC
EXTRN	__security_cookie:QWORD
EXTRN	_fltused:DWORD
pdata	SEGMENT
$pdata$__dt__6AnimalFv DD imagerel __dt__6AnimalFv
	DD	imagerel __dt__6AnimalFv+85
	DD	imagerel $unwind$__dt__6AnimalFv
$pdata$main DD	imagerel $LN14
	DD	imagerel $LN14+1065
	DD	imagerel $unwind$main
$pdata$__dt__4BirdFv DD imagerel __dt__4BirdFv
	DD	imagerel __dt__4BirdFv+122
	DD	imagerel $unwind$__dt__4BirdFv
$pdata$__dt__3DogFv DD imagerel __dt__3DogFv
	DD	imagerel __dt__3DogFv+122
	DD	imagerel $unwind$__dt__3DogFv
pdata	ENDS
;	COMDAT __real@4010000000000000
CONST	SEGMENT
__real@4010000000000000 DQ 04010000000000000r	; 4
CONST	ENDS
;	COMDAT __real@4008000000000000
CONST	SEGMENT
__real@4008000000000000 DQ 04008000000000000r	; 3
CONST	ENDS
;	COMDAT __real@4000000000000000
CONST	SEGMENT
__real@4000000000000000 DQ 04000000000000000r	; 2
CONST	ENDS
;	COMDAT __real@3ff0000000000000
CONST	SEGMENT
__real@3ff0000000000000 DQ 03ff0000000000000r	; 1
CONST	ENDS
_DATA	SEGMENT
$SG8012	DB	'A %-4s has %d legs and says ''%s''', 0aH, 00H
	ORG $+6
$SG8013	DB	'a+b = (%g, %g)   a.b = %g', 0aH, 00H
	ORG $+1
$SG8060	DB	'bird', 00H
	ORG $+3
$SG8064	DB	'tweet', 00H
	ORG $+2
$SG8085	DB	'dog', 00H
$SG8089	DB	'woof', 00H
	ORG $+3
$SG8093	DB	'animal', 00H
	ORG $+1
$SG8097	DB	'...', 00H
_DATA	ENDS
voltbl	SEGMENT
_volmd	DD	0ffffffffH
	DDSymXIndex: 	FLAT:main
	DD	014H
	DD	040fH
voltbl	ENDS
xdata	SEGMENT
$unwind$__dt__6AnimalFv DD 010d01H
	DD	0420dH
$unwind$main DD	041c19H
	DD	01f010aH
	DD	060027003H
	DD	imagerel __GSHandlerCheck
	DD	0e8H
$unwind$__dt__4BirdFv DD 010d01H
	DD	0420dH
$unwind$__dt__3DogFv DD 010d01H
	DD	0420dH
xdata	ENDS
; Function compile flags: /Odtp
; File C:\Users\Diana\pg\cfront-3\zoo_ext.c
_TEXT	SEGMENT
__0this$ = 8
kind__3DogFv PROC

; 193  : static const char *kind__3DogFv (struct Dog *__0this ){ return (const char *)"dog";

  00000	48 89 4c 24 08	 mov	 QWORD PTR [rsp+8], rcx
  00005	48 8d 05 00 00
	00 00		 lea	 rax, OFFSET FLAT:$SG8085

; 194  : }

  0000c	c3		 ret	 0
kind__3DogFv ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\Diana\pg\cfront-3\zoo_ext.c
_TEXT	SEGMENT
__0this$ = 8
sound__3DogFv PROC

; 196  : static const char *sound__3DogFv (struct Dog *__0this ){ return (const char *)"woof";

  00000	48 89 4c 24 08	 mov	 QWORD PTR [rsp+8], rcx
  00005	48 8d 05 00 00
	00 00		 lea	 rax, OFFSET FLAT:$SG8089

; 197  : 
; 198  : }

  0000c	c3		 ret	 0
sound__3DogFv ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\Diana\pg\cfront-3\zoo_ext.c
_TEXT	SEGMENT
__0this$ = 48
__0__free$ = 56
__dt__3DogFv PROC

; 183  : int __0__free ){ 

  00000	89 54 24 10	 mov	 DWORD PTR [rsp+16], edx
  00004	48 89 4c 24 08	 mov	 QWORD PTR [rsp+8], rcx
  00009	48 83 ec 28	 sub	 rsp, 40			; 00000028H

; 184  : if (__0this ){ __0this -> __vptr__6Animal = (struct __mptr *) __ptbl_vec___c_Users_Diana_pg_cfront_3_demo_zoo_C_[1];

  0000d	48 83 7c 24 30
	00		 cmp	 QWORD PTR __0this$[rsp], 0
  00013	74 60		 je	 SHORT $LN2@dt__3DogFv
  00015	b8 08 00 00 00	 mov	 eax, 8
  0001a	48 6b c0 01	 imul	 rax, rax, 1
  0001e	48 8d 0d 00 00
	00 00		 lea	 rcx, OFFSET FLAT:__ptbl_vec___c_Users_Diana_pg_cfront_3_demo_zoo_C_
  00025	48 8b 54 24 30	 mov	 rdx, QWORD PTR __0this$[rsp]
  0002a	48 8b 04 01	 mov	 rax, QWORD PTR [rcx+rax]
  0002e	48 89 42 08	 mov	 QWORD PTR [rdx+8], rax

; 185  : 
; 186  : if (__0this ){ ( ((((struct Animal *)__0this ))?(((void )( ((((struct Animal *)__0this ))-> __vptr__6Animal = (struct __mptr *) __ptbl_vec___c_Users_Diana_pg_cfront_3_demo_zoo_C_[0]), ((((struct Animal *)__0this ))?(((void )(((void

  00032	48 83 7c 24 30
	00		 cmp	 QWORD PTR __0this$[rsp], 0
  00038	74 3b		 je	 SHORT $LN3@dt__3DogFv
  0003a	48 83 7c 24 30
	00		 cmp	 QWORD PTR __0this$[rsp], 0
  00040	74 1d		 je	 SHORT $LN8@dt__3DogFv
  00042	b8 08 00 00 00	 mov	 eax, 8
  00047	48 6b c0 00	 imul	 rax, rax, 0
  0004b	48 8d 0d 00 00
	00 00		 lea	 rcx, OFFSET FLAT:__ptbl_vec___c_Users_Diana_pg_cfront_3_demo_zoo_C_
  00052	48 8b 54 24 30	 mov	 rdx, QWORD PTR __0this$[rsp]
  00057	48 8b 04 01	 mov	 rax, QWORD PTR [rcx+rax]
  0005b	48 89 42 08	 mov	 QWORD PTR [rdx+8], rax
$LN8@dt__3DogFv:

; 187  : )0 )))):(((void )0 )))) )):(((void )0 )))) ;
; 188  : 
; 189  : if (__0__free & 1)__dl__FPv ( (void *)__0this ) ;

  0005f	8b 44 24 38	 mov	 eax, DWORD PTR __0__free$[rsp]
  00063	83 e0 01	 and	 eax, 1
  00066	85 c0		 test	 eax, eax
  00068	74 0b		 je	 SHORT $LN4@dt__3DogFv
  0006a	48 8b 4c 24 30	 mov	 rcx, QWORD PTR __0this$[rsp]
  0006f	e8 00 00 00 00	 call	 __dl__FPv
  00074	90		 npad	 1
$LN4@dt__3DogFv:
$LN3@dt__3DogFv:
$LN2@dt__3DogFv:

; 190  : } } 
; 191  : }

  00075	48 83 c4 28	 add	 rsp, 40			; 00000028H
  00079	c3		 ret	 0
__dt__3DogFv ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\Diana\pg\cfront-3\zoo_ext.c
_TEXT	SEGMENT
__0this$ = 8
kind__4BirdFv PROC

; 175  : static const char *kind__4BirdFv (struct Bird *__0this ){ return (const char *)"bird";

  00000	48 89 4c 24 08	 mov	 QWORD PTR [rsp+8], rcx
  00005	48 8d 05 00 00
	00 00		 lea	 rax, OFFSET FLAT:$SG8060

; 176  : }

  0000c	c3		 ret	 0
kind__4BirdFv ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\Diana\pg\cfront-3\zoo_ext.c
_TEXT	SEGMENT
__0this$ = 8
sound__4BirdFv PROC

; 178  : static const char *sound__4BirdFv (struct Bird *__0this ){ return (const char *)"tweet";

  00000	48 89 4c 24 08	 mov	 QWORD PTR [rsp+8], rcx
  00005	48 8d 05 00 00
	00 00		 lea	 rax, OFFSET FLAT:$SG8064

; 179  : 
; 180  : }

  0000c	c3		 ret	 0
sound__4BirdFv ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\Diana\pg\cfront-3\zoo_ext.c
_TEXT	SEGMENT
__0this$ = 48
__0__free$ = 56
__dt__4BirdFv PROC

; 165  : int __0__free ){ 

  00000	89 54 24 10	 mov	 DWORD PTR [rsp+16], edx
  00004	48 89 4c 24 08	 mov	 QWORD PTR [rsp+8], rcx
  00009	48 83 ec 28	 sub	 rsp, 40			; 00000028H

; 166  : if (__0this ){ __0this -> __vptr__6Animal = (struct __mptr *) __ptbl_vec___c_Users_Diana_pg_cfront_3_demo_zoo_C_[2];

  0000d	48 83 7c 24 30
	00		 cmp	 QWORD PTR __0this$[rsp], 0
  00013	74 60		 je	 SHORT $LN2@dt__4BirdF
  00015	b8 08 00 00 00	 mov	 eax, 8
  0001a	48 6b c0 02	 imul	 rax, rax, 2
  0001e	48 8d 0d 00 00
	00 00		 lea	 rcx, OFFSET FLAT:__ptbl_vec___c_Users_Diana_pg_cfront_3_demo_zoo_C_
  00025	48 8b 54 24 30	 mov	 rdx, QWORD PTR __0this$[rsp]
  0002a	48 8b 04 01	 mov	 rax, QWORD PTR [rcx+rax]
  0002e	48 89 42 08	 mov	 QWORD PTR [rdx+8], rax

; 167  : 
; 168  : if (__0this ){ ( ((((struct Animal *)__0this ))?(((void )( ((((struct Animal *)__0this ))-> __vptr__6Animal = (struct __mptr *) __ptbl_vec___c_Users_Diana_pg_cfront_3_demo_zoo_C_[0]), ((((struct Animal *)__0this ))?(((void )(((void

  00032	48 83 7c 24 30
	00		 cmp	 QWORD PTR __0this$[rsp], 0
  00038	74 3b		 je	 SHORT $LN3@dt__4BirdF
  0003a	48 83 7c 24 30
	00		 cmp	 QWORD PTR __0this$[rsp], 0
  00040	74 1d		 je	 SHORT $LN8@dt__4BirdF
  00042	b8 08 00 00 00	 mov	 eax, 8
  00047	48 6b c0 00	 imul	 rax, rax, 0
  0004b	48 8d 0d 00 00
	00 00		 lea	 rcx, OFFSET FLAT:__ptbl_vec___c_Users_Diana_pg_cfront_3_demo_zoo_C_
  00052	48 8b 54 24 30	 mov	 rdx, QWORD PTR __0this$[rsp]
  00057	48 8b 04 01	 mov	 rax, QWORD PTR [rcx+rax]
  0005b	48 89 42 08	 mov	 QWORD PTR [rdx+8], rax
$LN8@dt__4BirdF:

; 169  : )0 )))):(((void )0 )))) )):(((void )0 )))) ;
; 170  : 
; 171  : if (__0__free & 1)__dl__FPv ( (void *)__0this ) ;

  0005f	8b 44 24 38	 mov	 eax, DWORD PTR __0__free$[rsp]
  00063	83 e0 01	 and	 eax, 1
  00066	85 c0		 test	 eax, eax
  00068	74 0b		 je	 SHORT $LN4@dt__4BirdF
  0006a	48 8b 4c 24 30	 mov	 rcx, QWORD PTR __0this$[rsp]
  0006f	e8 00 00 00 00	 call	 __dl__FPv
  00074	90		 npad	 1
$LN4@dt__4BirdF:
$LN3@dt__4BirdF:
$LN2@dt__4BirdF:

; 172  : } } 
; 173  : }

  00075	48 83 c4 28	 add	 rsp, 40			; 00000028H
  00079	c3		 ret	 0
__dt__4BirdFv ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\Diana\pg\cfront-3\zoo_ext.c
_TEXT	SEGMENT
__1i$1 = 32
__0__X9$2 = 40
__0__X10$3 = 48
__0__X3$4 = 56
__0__X5$5 = 64
__1zoo$6 = 72
tv78 = 88
tv130 = 92
tv83 = 96
tv135 = 104
tv213 = 112
tv146 = 120
tv212 = 128
__2__X7$7 = 136
__2__X8$8 = 144
__1a$9 = 152
__1b$10 = 168
__2__X11$11 = 184
__0__X__V600qywmaaibmo$12 = 200
__1c$13 = 216
__$ArrayPad$ = 232
main	PROC

; 75   : int main (void ){ _main(); 

$LN14:
  00000	40 56		 push	 rsi
  00002	57		 push	 rdi
  00003	48 81 ec f8 00
	00 00		 sub	 rsp, 248		; 000000f8H
  0000a	48 8b 05 00 00
	00 00		 mov	 rax, QWORD PTR __security_cookie
  00011	48 33 c4	 xor	 rax, rsp
  00014	48 89 84 24 e8
	00 00 00	 mov	 QWORD PTR __$ArrayPad$[rsp], rax
  0001c	e8 00 00 00 00	 call	 _main
  00021	90		 npad	 1

; 76   : { 
; 77   : struct Animal *__1zoo [2];
; 78   : 
; 79   : struct Dog *__0__X9 ;
; 80   : 
; 81   : struct Animal *__0__X3 ;
; 82   : 
; 83   : struct Bird *__0__X10 ;
; 84   : 
; 85   : struct Animal *__0__X5 ;
; 86   : 
; 87   : (__1zoo [0 ])= (struct Animal *)( (__0__X9 = 0 ), ( ((__0__X9 || (__0__X9 = (struct Dog *)__nw__FUl ( (unsigned long )(sizeof (struct Dog)))

  00022	48 c7 44 24 28
	00 00 00 00	 mov	 QWORD PTR __0__X9$2[rsp], 0
  0002b	48 83 7c 24 28
	00		 cmp	 QWORD PTR __0__X9$2[rsp], 0
  00031	75 25		 jne	 SHORT $LN6@main
  00033	b9 10 00 00 00	 mov	 ecx, 16
  00038	e8 00 00 00 00	 call	 __nw__FUl
  0003d	48 89 44 24 28	 mov	 QWORD PTR __0__X9$2[rsp], rax
  00042	48 83 7c 24 28
	00		 cmp	 QWORD PTR __0__X9$2[rsp], 0
  00048	75 0e		 jne	 SHORT $LN6@main
  0004a	48 c7 44 24 60
	00 00 00 00	 mov	 QWORD PTR tv83[rsp], 0
  00053	e9 98 00 00 00	 jmp	 $LN9@main
$LN6@main:
  00058	48 8b 44 24 28	 mov	 rax, QWORD PTR __0__X9$2[rsp]
  0005d	48 89 44 24 38	 mov	 QWORD PTR __0__X3$4[rsp], rax
  00062	48 83 7c 24 38
	00		 cmp	 QWORD PTR __0__X3$4[rsp], 0
  00068	75 21		 jne	 SHORT $LN7@main
  0006a	b9 10 00 00 00	 mov	 ecx, 16
  0006f	e8 00 00 00 00	 call	 __nw__FUl
  00074	48 89 44 24 38	 mov	 QWORD PTR __0__X3$4[rsp], rax
  00079	48 83 7c 24 38
	00		 cmp	 QWORD PTR __0__X3$4[rsp], 0
  0007f	75 0a		 jne	 SHORT $LN7@main
  00081	c7 44 24 58 00
	00 00 00	 mov	 DWORD PTR tv78[rsp], 0
  00089	eb 30		 jmp	 SHORT $LN8@main
$LN7@main:
  0008b	b8 08 00 00 00	 mov	 eax, 8
  00090	48 6b c0 00	 imul	 rax, rax, 0
  00094	48 8d 0d 00 00
	00 00		 lea	 rcx, OFFSET FLAT:__ptbl_vec___c_Users_Diana_pg_cfront_3_demo_zoo_C_
  0009b	48 8b 54 24 38	 mov	 rdx, QWORD PTR __0__X3$4[rsp]
  000a0	48 8b 04 01	 mov	 rax, QWORD PTR [rcx+rax]
  000a4	48 89 42 08	 mov	 QWORD PTR [rdx+8], rax
  000a8	48 8b 44 24 38	 mov	 rax, QWORD PTR __0__X3$4[rsp]
  000ad	c7 00 04 00 00
	00		 mov	 DWORD PTR [rax], 4
  000b3	c7 44 24 58 04
	00 00 00	 mov	 DWORD PTR tv78[rsp], 4
$LN8@main:
  000bb	48 8b 44 24 38	 mov	 rax, QWORD PTR __0__X3$4[rsp]
  000c0	48 89 44 24 28	 mov	 QWORD PTR __0__X9$2[rsp], rax
  000c5	b8 08 00 00 00	 mov	 eax, 8
  000ca	48 6b c0 01	 imul	 rax, rax, 1
  000ce	48 8d 0d 00 00
	00 00		 lea	 rcx, OFFSET FLAT:__ptbl_vec___c_Users_Diana_pg_cfront_3_demo_zoo_C_
  000d5	48 8b 54 24 28	 mov	 rdx, QWORD PTR __0__X9$2[rsp]
  000da	48 8b 04 01	 mov	 rax, QWORD PTR [rcx+rax]
  000de	48 89 42 08	 mov	 QWORD PTR [rdx+8], rax
  000e2	48 8b 44 24 28	 mov	 rax, QWORD PTR __0__X9$2[rsp]
  000e7	48 8b 40 08	 mov	 rax, QWORD PTR [rax+8]
  000eb	48 89 44 24 60	 mov	 QWORD PTR tv83[rsp], rax
$LN9@main:
  000f0	b8 08 00 00 00	 mov	 eax, 8
  000f5	48 6b c0 00	 imul	 rax, rax, 0
  000f9	48 8b 4c 24 28	 mov	 rcx, QWORD PTR __0__X9$2[rsp]
  000fe	48 89 4c 04 48	 mov	 QWORD PTR __1zoo$6[rsp+rax], rcx

; 88   : ))?( (__0__X9 = (struct Dog *)( (__0__X3 = (((struct Animal *)__0__X9 ))), ( ((__0__X3 || (__0__X3 = (struct Animal *)__nw__FUl ( (unsigned long
; 89   : )(sizeof (struct Animal))) ))?( (__0__X3 -> __vptr__6Animal = (struct __mptr *) __ptbl_vec___c_Users_Diana_pg_cfront_3_demo_zoo_C_[0]), (__0__X3 -> legs__6Animal = 4 )) :0 ), __0__X3 ) ) ),
; 90   : (__0__X9 -> __vptr__6Animal = (struct __mptr *) __ptbl_vec___c_Users_Diana_pg_cfront_3_demo_zoo_C_[1])) :0 ), __0__X9 ) ) ;
; 91   : (__1zoo [1 ])= (struct Animal *)( (__0__X10 = 0 ), ( ((__0__X10 || (__0__X10 = (struct Bird *)__nw__FUl ( (unsigned long )(sizeof (struct Bird)))

  00103	48 c7 44 24 30
	00 00 00 00	 mov	 QWORD PTR __0__X10$3[rsp], 0
  0010c	48 83 7c 24 30
	00		 cmp	 QWORD PTR __0__X10$3[rsp], 0
  00112	75 25		 jne	 SHORT $LN10@main
  00114	b9 10 00 00 00	 mov	 ecx, 16
  00119	e8 00 00 00 00	 call	 __nw__FUl
  0011e	48 89 44 24 30	 mov	 QWORD PTR __0__X10$3[rsp], rax
  00123	48 83 7c 24 30
	00		 cmp	 QWORD PTR __0__X10$3[rsp], 0
  00129	75 0e		 jne	 SHORT $LN10@main
  0012b	48 c7 44 24 68
	00 00 00 00	 mov	 QWORD PTR tv135[rsp], 0
  00134	e9 98 00 00 00	 jmp	 $LN13@main
$LN10@main:
  00139	48 8b 44 24 30	 mov	 rax, QWORD PTR __0__X10$3[rsp]
  0013e	48 89 44 24 40	 mov	 QWORD PTR __0__X5$5[rsp], rax
  00143	48 83 7c 24 40
	00		 cmp	 QWORD PTR __0__X5$5[rsp], 0
  00149	75 21		 jne	 SHORT $LN11@main
  0014b	b9 10 00 00 00	 mov	 ecx, 16
  00150	e8 00 00 00 00	 call	 __nw__FUl
  00155	48 89 44 24 40	 mov	 QWORD PTR __0__X5$5[rsp], rax
  0015a	48 83 7c 24 40
	00		 cmp	 QWORD PTR __0__X5$5[rsp], 0
  00160	75 0a		 jne	 SHORT $LN11@main
  00162	c7 44 24 5c 00
	00 00 00	 mov	 DWORD PTR tv130[rsp], 0
  0016a	eb 30		 jmp	 SHORT $LN12@main
$LN11@main:
  0016c	b8 08 00 00 00	 mov	 eax, 8
  00171	48 6b c0 00	 imul	 rax, rax, 0
  00175	48 8d 0d 00 00
	00 00		 lea	 rcx, OFFSET FLAT:__ptbl_vec___c_Users_Diana_pg_cfront_3_demo_zoo_C_
  0017c	48 8b 54 24 40	 mov	 rdx, QWORD PTR __0__X5$5[rsp]
  00181	48 8b 04 01	 mov	 rax, QWORD PTR [rcx+rax]
  00185	48 89 42 08	 mov	 QWORD PTR [rdx+8], rax
  00189	48 8b 44 24 40	 mov	 rax, QWORD PTR __0__X5$5[rsp]
  0018e	c7 00 02 00 00
	00		 mov	 DWORD PTR [rax], 2
  00194	c7 44 24 5c 02
	00 00 00	 mov	 DWORD PTR tv130[rsp], 2
$LN12@main:
  0019c	48 8b 44 24 40	 mov	 rax, QWORD PTR __0__X5$5[rsp]
  001a1	48 89 44 24 30	 mov	 QWORD PTR __0__X10$3[rsp], rax
  001a6	b8 08 00 00 00	 mov	 eax, 8
  001ab	48 6b c0 02	 imul	 rax, rax, 2
  001af	48 8d 0d 00 00
	00 00		 lea	 rcx, OFFSET FLAT:__ptbl_vec___c_Users_Diana_pg_cfront_3_demo_zoo_C_
  001b6	48 8b 54 24 30	 mov	 rdx, QWORD PTR __0__X10$3[rsp]
  001bb	48 8b 04 01	 mov	 rax, QWORD PTR [rcx+rax]
  001bf	48 89 42 08	 mov	 QWORD PTR [rdx+8], rax
  001c3	48 8b 44 24 30	 mov	 rax, QWORD PTR __0__X10$3[rsp]
  001c8	48 8b 40 08	 mov	 rax, QWORD PTR [rax+8]
  001cc	48 89 44 24 68	 mov	 QWORD PTR tv135[rsp], rax
$LN13@main:
  001d1	b8 08 00 00 00	 mov	 eax, 8
  001d6	48 6b c0 01	 imul	 rax, rax, 1
  001da	48 8b 4c 24 30	 mov	 rcx, QWORD PTR __0__X10$3[rsp]
  001df	48 89 4c 04 48	 mov	 QWORD PTR __1zoo$6[rsp+rax], rcx

; 92   : ))?( (__0__X10 = (struct Bird *)( (__0__X5 = (((struct Animal *)__0__X10 ))), ( ((__0__X5 || (__0__X5 = (struct Animal *)__nw__FUl ( (unsigned long
; 93   : )(sizeof (struct Animal))) ))?( (__0__X5 -> __vptr__6Animal = (struct __mptr *) __ptbl_vec___c_Users_Diana_pg_cfront_3_demo_zoo_C_[0]), (__0__X5 -> legs__6Animal = 2 )) :0 ), __0__X5 ) ) ),
; 94   : (__0__X10 -> __vptr__6Animal = (struct __mptr *) __ptbl_vec___c_Users_Diana_pg_cfront_3_demo_zoo_C_[2])) :0 ), __0__X10 ) ) ;
; 95   : { { int __1i ;
; 96   : 
; 97   : __1i = 0 ;

  001e4	c7 44 24 20 00
	00 00 00	 mov	 DWORD PTR __1i$1[rsp], 0

; 98   : 
; 99   : for(;__1i < 2 ;__1i ++ ) 

  001ec	eb 0a		 jmp	 SHORT $LN4@main
$LN2@main:
  001ee	8b 44 24 20	 mov	 eax, DWORD PTR __1i$1[rsp]
  001f2	ff c0		 inc	 eax
  001f4	89 44 24 20	 mov	 DWORD PTR __1i$1[rsp], eax
$LN4@main:
  001f8	83 7c 24 20 02	 cmp	 DWORD PTR __1i$1[rsp], 2
  001fd	0f 8d da 00 00
	00		 jge	 $LN3@main

; 100  : ( printf ( (const char *)"A %-4s has %d legs and says '%s'\n", ((*(((const char

  00203	48 63 44 24 20	 movsxd	 rax, DWORD PTR __1i$1[rsp]
  00208	48 63 4c 24 20	 movsxd	 rcx, DWORD PTR __1i$1[rsp]
  0020d	48 8b 4c cc 48	 mov	 rcx, QWORD PTR __1zoo$6[rsp+rcx*8]
  00212	ba 10 00 00 00	 mov	 edx, 16
  00217	48 6b d2 02	 imul	 rdx, rdx, 2
  0021b	48 8b 49 08	 mov	 rcx, QWORD PTR [rcx+8]
  0021f	48 0f bf 0c 11	 movsx	 rcx, WORD PTR [rcx+rdx]
  00224	48 03 4c c4 48	 add	 rcx, QWORD PTR __1zoo$6[rsp+rax*8]
  00229	48 8b c1	 mov	 rax, rcx
  0022c	48 63 4c 24 20	 movsxd	 rcx, DWORD PTR __1i$1[rsp]
  00231	48 8b 4c cc 48	 mov	 rcx, QWORD PTR __1zoo$6[rsp+rcx*8]
  00236	ba 10 00 00 00	 mov	 edx, 16
  0023b	48 6b d2 02	 imul	 rdx, rdx, 2
  0023f	48 8b 49 08	 mov	 rcx, QWORD PTR [rcx+8]
  00243	48 89 4c 24 70	 mov	 QWORD PTR tv213[rsp], rcx
  00248	48 8b c8	 mov	 rcx, rax
  0024b	48 8b 44 24 70	 mov	 rax, QWORD PTR tv213[rsp]
  00250	ff 54 10 08	 call	 QWORD PTR [rax+rdx+8]
  00254	48 89 44 24 78	 mov	 QWORD PTR tv146[rsp], rax
  00259	48 63 4c 24 20	 movsxd	 rcx, DWORD PTR __1i$1[rsp]
  0025e	48 8b 4c cc 48	 mov	 rcx, QWORD PTR __1zoo$6[rsp+rcx*8]
  00263	48 89 8c 24 80
	00 00 00	 mov	 QWORD PTR tv212[rsp], rcx
  0026b	48 63 54 24 20	 movsxd	 rdx, DWORD PTR __1i$1[rsp]
  00270	4c 63 44 24 20	 movsxd	 r8, DWORD PTR __1i$1[rsp]
  00275	4e 8b 44 c4 48	 mov	 r8, QWORD PTR __1zoo$6[rsp+r8*8]
  0027a	41 b9 10 00 00
	00		 mov	 r9d, 16
  00280	4d 6b c9 03	 imul	 r9, r9, 3
  00284	4d 8b 40 08	 mov	 r8, QWORD PTR [r8+8]
  00288	4f 0f bf 04 08	 movsx	 r8, WORD PTR [r8+r9]
  0028d	4c 03 44 d4 48	 add	 r8, QWORD PTR __1zoo$6[rsp+rdx*8]
  00292	49 8b d0	 mov	 rdx, r8
  00295	4c 63 44 24 20	 movsxd	 r8, DWORD PTR __1i$1[rsp]
  0029a	4e 8b 44 c4 48	 mov	 r8, QWORD PTR __1zoo$6[rsp+r8*8]
  0029f	41 b9 10 00 00
	00		 mov	 r9d, 16
  002a5	4d 6b c9 03	 imul	 r9, r9, 3
  002a9	4d 8b 40 08	 mov	 r8, QWORD PTR [r8+8]
  002ad	48 8b ca	 mov	 rcx, rdx
  002b0	43 ff 54 08 08	 call	 QWORD PTR [r8+r9+8]
  002b5	48 8b 4c 24 78	 mov	 rcx, QWORD PTR tv146[rsp]
  002ba	4c 8b c9	 mov	 r9, rcx
  002bd	48 8b 8c 24 80
	00 00 00	 mov	 rcx, QWORD PTR tv212[rsp]
  002c5	44 8b 01	 mov	 r8d, DWORD PTR [rcx]
  002c8	48 8b d0	 mov	 rdx, rax
  002cb	48 8d 0d 00 00
	00 00		 lea	 rcx, OFFSET FLAT:$SG8012
  002d2	e8 00 00 00 00	 call	 printf
  002d7	90		 npad	 1
  002d8	e9 11 ff ff ff	 jmp	 $LN2@main
$LN3@main:

; 101  : *(*)(struct Animal *__0this ))((__1zoo [__1i ])-> __vptr__6Animal [3]).f))))( ((struct Animal *)((((char *)(__1zoo [__1i ])))+ ((__1zoo [__1i ])-> __vptr__6Animal [3]).d))) , (__1zoo [__1i ])-> legs__6Animal , ((*(((const char *(*)(struct
; 102  : Animal *__0this ))((__1zoo [__1i ])-> __vptr__6Animal [2]).f))))( ((struct Animal *)((((char *)(__1zoo [__1i ])))+ ((__1zoo [__1i ])-> __vptr__6Animal [2]).d))) ) , (((void )0 ))) ;
; 103  : 
; 104  : { struct Vec2 __1a ;
; 105  : 
; 106  : struct Vec2 __1b ;
; 107  : struct Vec2 __1c ;
; 108  : 
; 109  : struct Vec2 __2__X11 ;
; 110  : 
; 111  : double __2__X7 ;
; 112  : 
; 113  : double __2__X8 ;
; 114  : 
; 115  : struct Vec2 __0__X__V600qywmaaibmo ;
; 116  : 
; 117  : ( (( ((& __1a )-> x__4Vec2 = ((double )1 )), ((& __1a )-> y__4Vec2 = ((double )2 ))) ), (&

  002dd	f2 0f 10 05 00
	00 00 00	 movsd	 xmm0, QWORD PTR __real@3ff0000000000000
  002e5	f2 0f 11 84 24
	98 00 00 00	 movsd	 QWORD PTR __1a$9[rsp], xmm0
  002ee	f2 0f 10 05 00
	00 00 00	 movsd	 xmm0, QWORD PTR __real@4000000000000000
  002f6	f2 0f 11 84 24
	a0 00 00 00	 movsd	 QWORD PTR __1a$9[rsp+8], xmm0

; 118  : __1a )) ;
; 119  : 
; 120  : ( (( ((& __1b )-> x__4Vec2 = ((double )3 )), ((& __1b )-> y__4Vec2 = ((double )4 ))) ), (&

  002ff	f2 0f 10 05 00
	00 00 00	 movsd	 xmm0, QWORD PTR __real@4008000000000000
  00307	f2 0f 11 84 24
	a8 00 00 00	 movsd	 QWORD PTR __1b$10[rsp], xmm0
  00310	f2 0f 10 05 00
	00 00 00	 movsd	 xmm0, QWORD PTR __real@4010000000000000
  00318	f2 0f 11 84 24
	b0 00 00 00	 movsd	 QWORD PTR __1b$10[rsp+8], xmm0

; 121  : __1b )) ;
; 122  : __1c = ( (__2__X11 = __1b ), ( ( ( (__2__X7 = ((& __1a )-> x__4Vec2 + __2__X11 . x__4Vec2 )), (

  00321	48 8d 84 24 b8
	00 00 00	 lea	 rax, QWORD PTR __2__X11$11[rsp]
  00329	48 8d 8c 24 a8
	00 00 00	 lea	 rcx, QWORD PTR __1b$10[rsp]
  00331	48 8b f8	 mov	 rdi, rax
  00334	48 8b f1	 mov	 rsi, rcx
  00337	b9 10 00 00 00	 mov	 ecx, 16
  0033c	f3 a4		 rep movsb
  0033e	f2 0f 10 84 24
	98 00 00 00	 movsd	 xmm0, QWORD PTR __1a$9[rsp]
  00347	f2 0f 58 84 24
	b8 00 00 00	 addsd	 xmm0, QWORD PTR __2__X11$11[rsp]
  00350	f2 0f 11 84 24
	88 00 00 00	 movsd	 QWORD PTR __2__X7$7[rsp], xmm0
  00359	f2 0f 10 84 24
	a0 00 00 00	 movsd	 xmm0, QWORD PTR __1a$9[rsp+8]
  00362	f2 0f 58 84 24
	c0 00 00 00	 addsd	 xmm0, QWORD PTR __2__X11$11[rsp+8]
  0036b	f2 0f 11 84 24
	90 00 00 00	 movsd	 QWORD PTR __2__X8$8[rsp], xmm0
  00374	f2 0f 10 84 24
	88 00 00 00	 movsd	 xmm0, QWORD PTR __2__X7$7[rsp]
  0037d	f2 0f 11 84 24
	c8 00 00 00	 movsd	 QWORD PTR __0__X__V600qywmaaibmo$12[rsp], xmm0
  00386	f2 0f 10 84 24
	90 00 00 00	 movsd	 xmm0, QWORD PTR __2__X8$8[rsp]
  0038f	f2 0f 11 84 24
	d0 00 00 00	 movsd	 QWORD PTR __0__X__V600qywmaaibmo$12[rsp+8], xmm0
  00398	48 8d 84 24 d8
	00 00 00	 lea	 rax, QWORD PTR __1c$13[rsp]
  003a0	48 8d 8c 24 c8
	00 00 00	 lea	 rcx, QWORD PTR __0__X__V600qywmaaibmo$12[rsp]
  003a8	48 8b f8	 mov	 rdi, rax
  003ab	48 8b f1	 mov	 rsi, rcx
  003ae	b9 10 00 00 00	 mov	 ecx, 16
  003b3	f3 a4		 rep movsb

; 123  : (__2__X8 = ((& __1a )-> y__4Vec2 + __2__X11 . y__4Vec2 )), ( (( ((& __0__X__V600qywmaaibmo )-> x__4Vec2 = __2__X7 ), ((& __0__X__V600qywmaaibmo )->
; 124  : y__4Vec2 = __2__X8 )) ), (& __0__X__V600qywmaaibmo )) ) ) , __0__X__V600qywmaaibmo ) ) ) ;
; 125  : printf ( (const char *)"a+b = (%g, %g)   a.b = %g\n", __1c . x__4Vec2 , __1c . y__4Vec2 , ( (((&

  003b5	f2 0f 10 84 24
	98 00 00 00	 movsd	 xmm0, QWORD PTR __1a$9[rsp]
  003be	f2 0f 59 84 24
	a8 00 00 00	 mulsd	 xmm0, QWORD PTR __1b$10[rsp]
  003c7	f2 0f 10 8c 24
	a0 00 00 00	 movsd	 xmm1, QWORD PTR __1a$9[rsp+8]
  003d0	f2 0f 59 8c 24
	b0 00 00 00	 mulsd	 xmm1, QWORD PTR __1b$10[rsp+8]
  003d9	f2 0f 58 c1	 addsd	 xmm0, xmm1
  003dd	0f 28 d8	 movaps	 xmm3, xmm0
  003e0	66 49 0f 7e d9	 movq	 r9, xmm3
  003e5	f2 0f 10 94 24
	e0 00 00 00	 movsd	 xmm2, QWORD PTR __1c$13[rsp+8]
  003ee	66 49 0f 7e d0	 movq	 r8, xmm2
  003f3	f2 0f 10 8c 24
	d8 00 00 00	 movsd	 xmm1, QWORD PTR __1c$13[rsp]
  003fc	66 48 0f 7e ca	 movq	 rdx, xmm1
  00401	48 8d 0d 00 00
	00 00		 lea	 rcx, OFFSET FLAT:$SG8013
  00408	e8 00 00 00 00	 call	 printf

; 126  : __1a )-> x__4Vec2 * ((*((struct Vec2 *)(& __1b )))). x__4Vec2 )+ ((& __1a )-> y__4Vec2 * ((*((struct Vec2 *)(& __1b )))). y__4Vec2 ))) )
; 127  : ;
; 128  : return 0 ;

  0040d	33 c0		 xor	 eax, eax

; 129  : 
; 130  : }
; 131  : 
; 132  : }
; 133  : 
; 134  : }
; 135  : }
; 136  : } static void __dt__4BirdFv (

  0040f	48 8b 8c 24 e8
	00 00 00	 mov	 rcx, QWORD PTR __$ArrayPad$[rsp]
  00417	48 33 cc	 xor	 rcx, rsp
  0041a	e8 00 00 00 00	 call	 __security_check_cookie
  0041f	48 81 c4 f8 00
	00 00		 add	 rsp, 248		; 000000f8H
  00426	5f		 pop	 rdi
  00427	5e		 pop	 rsi
  00428	c3		 ret	 0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\Diana\pg\cfront-3\zoo_ext.c
_TEXT	SEGMENT
__0this$ = 48
__0__free$ = 56
__dt__6AnimalFv PROC

; 209  : int __0__free ){ 

  00000	89 54 24 10	 mov	 DWORD PTR [rsp+16], edx
  00004	48 89 4c 24 08	 mov	 QWORD PTR [rsp+8], rcx
  00009	48 83 ec 28	 sub	 rsp, 40			; 00000028H

; 210  : if (__0this ){ 

  0000d	48 83 7c 24 30
	00		 cmp	 QWORD PTR __0this$[rsp], 0
  00013	74 3b		 je	 SHORT $LN2@dt__6Anima

; 211  : __0this -> __vptr__6Animal = (struct __mptr *) __ptbl_vec___c_Users_Diana_pg_cfront_3_demo_zoo_C_[0];

  00015	b8 08 00 00 00	 mov	 eax, 8
  0001a	48 6b c0 00	 imul	 rax, rax, 0
  0001e	48 8d 0d 00 00
	00 00		 lea	 rcx, OFFSET FLAT:__ptbl_vec___c_Users_Diana_pg_cfront_3_demo_zoo_C_
  00025	48 8b 54 24 30	 mov	 rdx, QWORD PTR __0this$[rsp]
  0002a	48 8b 04 01	 mov	 rax, QWORD PTR [rcx+rax]
  0002e	48 89 42 08	 mov	 QWORD PTR [rdx+8], rax

; 212  : 
; 213  : if (__0this )if (__0__free & 1)__dl__FPv ( (void *)__0this ) ;

  00032	48 83 7c 24 30
	00		 cmp	 QWORD PTR __0this$[rsp], 0
  00038	74 16		 je	 SHORT $LN3@dt__6Anima
  0003a	8b 44 24 38	 mov	 eax, DWORD PTR __0__free$[rsp]
  0003e	83 e0 01	 and	 eax, 1
  00041	85 c0		 test	 eax, eax
  00043	74 0b		 je	 SHORT $LN4@dt__6Anima
  00045	48 8b 4c 24 30	 mov	 rcx, QWORD PTR __0this$[rsp]
  0004a	e8 00 00 00 00	 call	 __dl__FPv
  0004f	90		 npad	 1
$LN4@dt__6Anima:
$LN3@dt__6Anima:
$LN2@dt__6Anima:

; 214  : } 
; 215  : }

  00050	48 83 c4 28	 add	 rsp, 40			; 00000028H
  00054	c3		 ret	 0
__dt__6AnimalFv ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\Diana\pg\cfront-3\zoo_ext.c
_TEXT	SEGMENT
__0this$ = 8
sound__6AnimalFv PROC

; 204  : static const char *sound__6AnimalFv (struct Animal *__0this ){ return (const char *)"...";

  00000	48 89 4c 24 08	 mov	 QWORD PTR [rsp+8], rcx
  00005	48 8d 05 00 00
	00 00		 lea	 rax, OFFSET FLAT:$SG8097

; 205  : 
; 206  : }

  0000c	c3		 ret	 0
sound__6AnimalFv ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\Diana\pg\cfront-3\zoo_ext.c
_TEXT	SEGMENT
__0this$ = 8
kind__6AnimalFv PROC

; 200  : static const char *kind__6AnimalFv (struct Animal *__0this ){ return (const char *)"animal";

  00000	48 89 4c 24 08	 mov	 QWORD PTR [rsp+8], rcx
  00005	48 8d 05 00 00
	00 00		 lea	 rax, OFFSET FLAT:$SG8093

; 201  : 
; 202  : }

  0000c	c3		 ret	 0
kind__6AnimalFv ENDP
_TEXT	ENDS
END
